// gRPC Server implements the UserService defined in proto/user.proto
//
// LEARNING NOTES:
// - gRPC uses HTTP/2 under the hood (multiplexing, header compression, bidirectional)
// - The server implements the interface generated by protoc
// - Interceptors (middleware) can add logging, auth, tracing to all RPCs
// - For C++ devs: gRPC originated at Google, the Go implementation is first-class
//
// Run: go run cmd/server/main.go
package main

import (
	"context"
	"fmt"
	"log"
	"net"
	"sync"

	pb "github.com/GauravAgarwalGarg/GrinWithGolang/src/10_distributed/grpc_service/pb"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
)

// server implements the UserServiceServer interface generated by protoc.
type server struct {
	pb.UnimplementedUserServiceServer
	mu    sync.RWMutex
	users map[string]*pb.UserResponse
}

func newServer() *server {
	return &server{
		users: make(map[string]*pb.UserResponse),
	}
}

// GetUser is a unary RPC one request, one response.
func (s *server) GetUser(ctx context.Context, req *pb.GetUserRequest) (*pb.UserResponse, error) {
	s.mu.RLock()
	defer s.mu.RUnlock()

	user, exists := s.users[req.Id]
	if !exists {
		// gRPC uses status codes (like HTTP but richer)
		return nil, status.Errorf(codes.NotFound, "user %s not found", req.Id)
	}
	return user, nil
}

// CreateUser stores a new user and returns it.
func (s *server) CreateUser(ctx context.Context, req *pb.CreateUserRequest) (*pb.UserResponse, error) {
	s.mu.Lock()
	defer s.mu.Unlock()

	id := generateID()
	user := &pb.UserResponse{
		Id:    id,
		Name:  req.Name,
		Email: req.Email,
	}
	s.users[id] = user

	log.Printf("Created user: %s (%s)", user.Name, user.Email)
	return user, nil
}

// ListUsers is a server-streaming RPC sends multiple responses for one request.
func (s *server) ListUsers(req *pb.ListUsersRequest, stream pb.UserService_ListUsersServer) error {
	s.mu.RLock()
	defer s.mu.RUnlock()

	for _, user := range s.users {
		if err := stream.Send(user); err != nil {
			return err
		}
	}
	return nil
}

// Simple ID generator (in production, use UUID or MongoDB ObjectID)
var idCounter int
var idMu sync.Mutex

func generateID() string {
	idMu.Lock()
	defer idMu.Unlock()
	idCounter++
	return fmt.Sprintf("user_%d", idCounter)
}

func main() {
	lis, err := net.Listen("tcp", ":50051")
	if err != nil {
		log.Fatalf("failed to listen: %v", err)
	}

	// Create gRPC server with optional interceptors
	grpcServer := grpc.NewServer(
	// Add interceptors here:
	// grpc.UnaryInterceptor(loggingInterceptor),
	)

	pb.RegisterUserServiceServer(grpcServer, newServer())

	log.Println("gRPC server listening on :50051")
	if err := grpcServer.Serve(lis); err != nil {
		log.Fatalf("failed to serve: %v", err)
	}
}
